# Generated by Django 4.2.2 on 2023-07-10 17:10

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('roomtype', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(validators=[users.models.validate_room_size])),
                ('class_room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=30)),
            ],
        ),
    ]
