# Generated by Django 4.2.2 on 2023-07-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='class_room_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='class_room_id'),
        ),
    ]
