# Generated by Django 4.2.2 on 2023-07-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_classroom_class_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='campus',
            field=models.CharField(choices=[('Middletown', 'Middletown'), ('Newburgh', 'Newburgh')], default='Middletown', max_length=30),
        ),
    ]
