# Generated by Django 4.2.2 on 2023-07-11 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_classroom_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='campus',
            field=models.CharField(choices=[('Middletown', 'Middletown'), ('Newburgh', 'Newburgh'), ('Other', 'Other')], default='Middletown', max_length=30),
        ),
        migrations.CreateModel(
            name='classes',
            fields=[
                ('CRN', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='class_room_id')),
                ('teacher_id', models.IntegerField()),
                ('description', models.TextField()),
                ('size', models.IntegerField()),
                ('registered_total', models.IntegerField()),
                ('wait_list', models.IntegerField()),
                ('time', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('day_of_week', models.CharField(max_length=30)),
                ('semester', models.CharField(max_length=30)),
                ('semester_year', models.IntegerField()),
                ('semester_session', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=100)),
                ('instruction_method', models.CharField(max_length=100)),
                ('campus', models.CharField(max_length=100)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('class_room_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.classroom')),
            ],
        ),
    ]
